version: '3.8'

services:
  target-api:
    build:
      context: .
      dockerfile: TargetDesafioTecnico/Dockerfile
    container_name: target_desafio_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: unless-stopped